### ISSUE TITLE
Resolve responsiveness issues

### ISSUE THREAD

**Issue by metzgr** [usedgov/usedgov.github.io#50]
<img width="389" alt="screen shot 2016-11-21 at 10 54 59 am" src="https://cloud.githubusercontent.com/assets/18745563/20489461/b878507c-afd8-11e6-9fb3-7ebb5f2bb5c9.png">
![Uploading Screen Shot 2016-11-21 at 10.54.49 AM.png…]()

**Comment by gbinal** [comment]
addressed by the redesign.
