### ISSUE TITLE
502 errors for CRDC and MBK Apis

### ISSUE THREAD

**Issue by JanelChumley** [usedgov/usedgov.github.io#79]
I'm developing ETLs with the CRDC and MBK Apis. It looks like the server for these APIs are down. Please see the screenshot. 
<img width="967" alt="screen shot 2019-01-04 at 9 32 27 am" src="https://user-images.githubusercontent.com/21347284/50696584-79736f80-1005-11e9-9360-786668ca19dc.png">

**Comment by willmhowes** [comment]
Hey Janel, were you ever able to access the servers for those APIs? And if not, did you manage to find a workaround short of downloading the entire dataset?

**Comment by JanelChumley** [comment]
The server is still throwing 502 errors. However, I'm no longer working on this project, so will close this issue.
